# Generated by Django 5.0.1 on 2024-01-24 06:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="cars.carbrand",
                verbose_name="Бренд",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="vin",
            field=models.CharField(
                default=uuid.UUID("5bc41e3f-72d6-43a8-8ed8-52fb21bc02fd"),
                max_length=200,
                verbose_name="VIN",
            ),
        ),
    ]
